### ISSUE TITLE
App crashes after adding two cities with the same name

### ISSUE THREAD

**Issue by discerno** [you-apps/ClockYou#282]
### Steps to reproduce

Add two cities with the same name to the world clock (e.g., Abidjan/Burkina Faso and Abidjan/Bouvet Island)

### Expected behavior

Two cities are added to the world clock.

### Actual behavior

The app crashes.

### Clock You version

7.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share adb crash logs for both issues.

**Comment by SuhasDissa** [comment]
Looks like a database error. We could use something else as the primary key.
```
FATAL EXCEPTION: DefaultDispatcher-worker-1
Process: com.bnyro.clock.debug, PID: 25951
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: timeZones.name (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:961)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.kt:42)
	at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.kt:68)
	at com.bnyro.clock.db.dao.TimeZonesDao_Impl$4.call(TimeZonesDao_Impl.java:98)
	at com.bnyro.clock.db.dao.TimeZonesDao_Impl$4.call(TimeZonesDao_Impl.java:93)
	at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:65)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.room.TransactionExecutor.execute$lambda$1$lambda$0(TransactionExecutor.kt:36)
	at androidx.room.TransactionExecutor.$r8$lambda$AympDHYBb78s7_N_9gRsXF0sHiw(Unknown Source:0)
	at androidx.room.TransactionExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f02020, Dispatchers.IO]
```
